INSERT INTO PRODUCT_CATEGORY VALUES('Electronics',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Clothing',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Home Appliances',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Toys',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Sports Equipment',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Books',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Jewelry',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Furniture',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Beauty Products',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Automotive Parts',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Kitchenware',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Office Supplies',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Health and Wellness',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Pet Supplies',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Garden Tools',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Musical Instruments',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Outdoor Gear',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Food and Beverages',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Baby Products',1,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Art and Craft Supplies',1,1);



INSERT INTO PRODUCT_CATEGORY VALUES('Electronics',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Clothing',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Home Appliances',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Toys',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Sports Equipment',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Books',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Jewelry',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Furniture',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Beauty Products',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Automotive Parts',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Kitchenware',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Office Supplies',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Health and Wellness',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Pet Supplies',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Garden Tools',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Musical Instruments',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Outdoor Gear',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Food and Beverages',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Baby Products',2,1);
INSERT INTO PRODUCT_CATEGORY VALUES('Art and Craft Supplies',2,1);















INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Smartphone X1',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(1,'Smartphone X1','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Laptop Pro A2',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(2,'Laptop Pro A2','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Smart TV 4K',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(3,'Smart TV 4K','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Wireless Headphones B3',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(4,'Wireless Headphones B3','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Digital Camera Z9',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(5,'Digital Camera Z9','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Gaming Console S6',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(6,'Gaming Console S6','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Tablet PC V2',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(7,'Tablet PC V2','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Bluetooth Speaker M8',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(8,'Bluetooth Speaker M8','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Fitness Tracker P4',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(9,'Fitness Tracker P4','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Drone Q7',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(10,'Drone Q7','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Portable Charger H5',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(11,'Portable Charger H5','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Robot Vacuum R3',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(12,'Robot Vacuum R3','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Smartwatch G1',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(13,'Smartwatch G1','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('VR Headset N6',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(14,'VR Headset N6','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Soundbar E8',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(15,'Soundbar E8','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Home Security Camera K3',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(16,'Home Security Camera K3','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Wireless Mouse T2',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(17,'Wireless Mouse T2','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Gaming Mousepad L7',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(18,'Gaming Mousepad L7','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Wireless Keyboard Y5',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(19,'Wireless Keyboard Y5','hameem','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('3D Printer C9',2,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(20,'3D Printer C9','hameem','Electronics',SYSDATE,10);































INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Smartphone X1',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(21,'Smartphone X1','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Laptop Pro A2',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(22,'Laptop Pro A2','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Smart TV 4K',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(23,'Smart TV 4K','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Wireless Headphones B3',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(24,'Wireless Headphones B3','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Digital Camera Z9',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(25,'Digital Camera Z9','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Gaming Console S6',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(26,'Gaming Console S6','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Tablet PC V2',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(27,'Tablet PC V2','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Bluetooth Speaker M8',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(28,'Bluetooth Speaker M8','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Fitness Tracker P4',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(29,'Fitness Tracker P4','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Drone Q7',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(30,'Drone Q7','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Portable Charger H5',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(31,'Portable Charger H5','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Robot Vacuum R3',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(32,'Robot Vacuum R3','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Smartwatch G1',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(33,'Smartwatch G1','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('VR Headset N6',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(34,'VR Headset N6','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Soundbar E8',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(35,'Soundbar E8','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Home Security Camera K3',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(36,'Home Security Camera K3','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Wireless Mouse T2',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(37,'Wireless Mouse T2','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Gaming Mousepad L7',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(38,'Gaming Mousepad L7','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Wireless Keyboard Y5',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(39,'Wireless Keyboard Y5','fihad','Electronics',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('3D Printer C9',1,1,'Electronics',40000,0,'black','M',1000);
INSERT INTO BUY_ORDER VALUES(40,'3D Printer C9','fihad','Electronics',SYSDATE,10);





















-- // cloathing
-- branch 1


INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Mens Suit Black',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(41,'Mens Suit Black','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Womens Dress Floral',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(42,'Womens Dress Floral','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('T-Shirt Plain White',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(43,'T-Shirt Plain White','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Jeans Slim Fit',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(44,'Jeans Slim Fit','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Winter Jacket Hooded',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(45,'Winter Jacket Hooded','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Sneakers High Tops',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(46,'Sneakers High Tops','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Sunglasses Aviator',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(47,'Sunglasses Aviator','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Scarf Cashmere',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(48,'Scarf Cashmere','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Socks Patterned',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(49,'Socks Patterned','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Swimsuit Bikini',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(50,'Swimsuit Bikini','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Hoodie Zip-Up',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(51,'Hoodie Zip-Up','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Polo Shirt Striped',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(52,'Polo Shirt Striped','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Dress Shoes Leather',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(53,'Dress Shoes Leather','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Workout Leggings',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(54,'Workout Leggings','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Baseball Cap Logo',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(55,'Baseball Cap Logo','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Denim Jacket Vintage',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(56,'Denim Jacket Vintage','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Raincoat Waterproof',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(57,'Raincoat Waterproof','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Pajama Set Cozy',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(58,'Pajama Set Cozy','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Blouse Silk',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(59,'Blouse Silk','fihad','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Shorts Cargo',1,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(60,'Shorts Cargo','fihad','Clothing',SYSDATE,10);



















-- branch 2

INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Mens Suit Black',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(61,'Mens Suit Black','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Womens Dress Floral',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(62,'Womens Dress Floral','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('T-Shirt Plain White',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(63,'T-Shirt Plain White','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Jeans Slim Fit',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(64,'Jeans Slim Fit','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Winter Jacket Hooded',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(65,'Winter Jacket Hooded','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Sneakers High Tops',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(66,'Sneakers High Tops','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Sunglasses Aviator',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(67,'Sunglasses Aviator','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Scarf Cashmere',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(68,'Scarf Cashmere','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Socks Patterned',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(69,'Socks Patterned','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Swimsuit Bikini',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(70,'Swimsuit Bikini','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Hoodie Zip-Up',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(71,'Hoodie Zip-Up','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Polo Shirt Striped',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(72,'Polo Shirt Striped','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Dress Shoes Leather',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(73,'Dress Shoes Leather','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Workout Leggings',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(74,'Workout Leggings','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Baseball Cap Logo',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(75,'Baseball Cap Logo','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Denim Jacket Vintage',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(76,'Denim Jacket Vintage','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Raincoat Waterproof',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(77,'Raincoat Waterproof','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Pajama Set Cozy',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(78,'Pajama Set Cozy','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Blouse Silk',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(79,'Blouse Silk','hameem','Clothing',SYSDATE,10);
INSERT INTO PRODUCT_INFO (PRODUCT_ID,BRANCH_ID,COMPANY_ID,CATEGORY_ID,UNIT_PRICE,QUANTITY,COLOR,PRODUCT_SIZE,DISCOUNT) VALUES ('Shorts Cargo',2,1,'Clothing',4000,0,'blue','M',500);
INSERT INTO BUY_ORDER VALUES(80,'Shorts Cargo','hameem','Clothing',SYSDATE,10);



-- 1. Electronics
-- * Smartphones
-- * Laptops
-- * Tablets
-- * TVs
-- * Computers
-- * Cameras
-- * Headphones
-- * Speakers
-- * Printers
-- * Scanners
-- * Routers
-- * Modems
-- * Hard drives
-- * Flash drives
-- * SD cards
-- * Batteries
-- * Cables
-- * Adapters
-- * Chargers
-- * Cleaning kits
-- * Screen protectors
-- * Cases

-- 2. Clothing
-- * Men's shirts
-- * Men's pants
-- * Men's shoes
-- * Women's shirts
-- * Women's pants
-- * Women's shoes
-- * Children's clothes
-- * Swimwear
-- * Underwear
-- * Socks
-- * Jackets
-- * Hats
-- * Gloves
-- * Scarves
-- * Belts
-- * Jewelry
-- * Watches
-- * Eyewear
-- * Bags
-- * Purses

-- 3. Home & Furniture
-- * Furniture
-- * Mattresses
-- * Pillows
-- * Bedding
-- * Bath towels
-- * Kitchen towels
-- * Rugs
-- * Blinds
-- * Curtains
-- * Sheets
-- * Pillowcases
-- * Towels
-- * Pots
-- * Pans
-- * Cutlery
-- * Dishes
-- * Glasses
-- * Cookware
-- * Bakeware
-- * Gadgets
-- * Home decor

-- 4. Toys & Games
-- * Dolls
-- * Action figures
-- * Building blocks
-- * Puzzles
-- * Board games
-- * Card games
-- * Outdoor toys
-- * Sports equipment
-- * Arts & crafts supplies
-- * Dress-up clothes
-- * Halloween costumes
-- * Christmas ornaments
-- * Party supplies

-- 5. Books
-- * Fiction
-- * Non-fiction
-- * Children's books
-- * Textbooks
-- * Cookbooks
-- * Reference books
-- * Magazines
-- * Newspapers
-- * Comics
-- * Graphic novels
-- * Audiobooks
-- * Ebooks

-- 6. Office Supplies
-- * Pens
-- * Pencils
-- * Markers
-- * Paper
-- * Notebooks
-- * Binders
-- * Highlighters
-- * Tape
-- * Scissors
-- * Staplers
-- * Hole punches
-- * Calculators
-- * Printer ink
-- * Toner cartridges
-- * Fax machines
-- * Scanners
-- * Paper shredders

-- 7. Sporting Goods
-- * Shoes
-- * Clothing
-- * Equipment
-- * Balls
-- * Bats
-- * Rackets
-- * Golf clubs
-- * Skis
-- * Snowboards
-- * Skateboards
-- * Bikes
-- * Fishing rods
-- * Camping gear

-- 8. Music
-- * Instruments
-- * Sheet music
-- * CDs
-- * Vinyl records
-- * MP3 players
-- * Headphones
-- * Speakers
-- * Amplifiers
-- * Cables
-- * Cases
-- * Stands
-- * Tuners
-- * Metronomes

-- 9. Jewelry
-- * Rings
-- * Necklaces
-- * Bracelets
-- * Earrings
-- * Watches
-- * Brooches
-- * Pins
-- * Pendants
-- * Charms
-- * Beads
-- * Chains
-- * Findings

-- 10. Cosmetics
-- * Makeup
-- * Skincare products
-- * Haircare products
-- * Bath & body products
-- * Perfumes
-- * Colognes
-- * Nail polish
-- * Cosmetics brushes
-- * Makeup remover
-- * Exfoliating products
-- * Toners
-- * Moisturizers
-- * Sunscreen

-- 11. Food & Beverages
-- * Groceries
-- * Snacks
-- * Drinks
-- * Condiments
-- * Baking supplies
-- * Coffee
-- * Tea
-- * Juice
-- * Beer
-- * Wine
-- * Liquor
-- * Soft drinks
-- * Energy drinks
-- * Vitamins

-- 12. Pets
-- * Food
-- * Toys
-- * Supplies
-- * Medications
-- * Collars
-- * Leashes
-- * Beds
-- * Crates
-- * Carriers
-- * Shampoo
-- * Conditioner
-- * Brushes
-- * Nail clippers
-- * Flea & tick


